site_name: KKLKK Wiki
site_description: Knowledge base
site_author: ZER0

theme:
  name: material
  language: en
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Predmeti:
    - Programiranje 2: programiranje-2.md
    - Osnovi Racunarske Tehnike: osnovi-racunarske-tehnike.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
